In [1]:
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
import sklearn.datasets
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
# from sklearn.model_selection import GridSearchCV
from sklearn.model_selection import RandomizedSearchCV

In [2]:
#load the data from the sklearn
breast_cancer_dataset = sklearn.datasets.load_breast_cancer()

In [3]:
print(breast_cancer_dataset)

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
        1.189e-01],
       [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
        8.902e-02],
       [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
        8.758e-02],
       ...,
       [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
        7.820e-02],
       [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
        1.240e-01],
       [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
        7.039e-02]]), 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
 

In [4]:
#load the data into the data frame
data_frame = pd.DataFrame(breast_cancer_dataset.data, columns=breast_cancer_dataset.feature_names)

In [5]:
data_frame.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst radius  worst texture  worst perimeter  \
0                 0.07871  ...         25.38          17.33           184.60   
1                 0.05667  ...         24.99          23.41           158.80   
2                 0.05999  ...         23.57          25.53           152.50   
3                 0.09744  ...         14.91          26.50            98.87   
4                 0.05883  ...         22.54          16.67           152.20   

   worst area  worst smoothness  worst compactness  worst concavity  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   worst concave points  worst symmetry  worst fractal dimension  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 30 columns]

In [6]:
# adding the target column to the data frame
data_frame['label'] = breast_cancer_dataset.target

In [7]:
data_frame.head()

mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0        17.99         10.38          122.80     1001.0          0.11840   
1        20.57         17.77          132.90     1326.0          0.08474   
2        19.69         21.25          130.00     1203.0          0.10960   
3        11.42         20.38           77.58      386.1          0.14250   
4        20.29         14.34          135.10     1297.0          0.10030   

   mean compactness  mean concavity  mean concave points  mean symmetry  \
0           0.27760          0.3001              0.14710         0.2419   
1           0.07864          0.0869              0.07017         0.1812   
2           0.15990          0.1974              0.12790         0.2069   
3           0.28390          0.2414              0.10520         0.2597   
4           0.13280          0.1980              0.10430         0.1809   

   mean fractal dimension  ...  worst texture  worst perimeter  worst area  \
0                 0.07871  ...          17.33           184.60      2019.0   
1                 0.05667  ...          23.41           158.80      1956.0   
2                 0.05999  ...          25.53           152.50      1709.0   
3                 0.09744  ...          26.50            98.87       567.7   
4                 0.05883  ...          16.67           152.20      1575.0   

   worst smoothness  worst compactness  worst concavity  worst concave points  \
0            0.1622             0.6656           0.7119                0.2654   
1            0.1238             0.1866           0.2416                0.1860   
2            0.1444             0.4245           0.4504                0.2430   
3            0.2098             0.8663           0.6869                0.2575   
4            0.1374             0.2050           0.4000                0.1625   

   worst symmetry  worst fractal dimension  label  
0          0.4601                  0.11890      0  
1          0.2750                  0.08902      0  
2          0.3613                  0.08758      0  
3          0.6638                  0.17300      0  
4          0.2364                  0.07678      0  

[5 rows x 31 columns]

In [8]:
data_frame.shape

(569, 31)

In [9]:
data_frame.isnull().sum()

mean radius                0
mean texture               0
mean perimeter             0
mean area                  0
mean smoothness            0
mean compactness           0
mean concavity             0
mean concave points        0
mean symmetry              0
mean fractal dimension     0
radius error               0
texture error              0
perimeter error            0
area error                 0
smoothness error           0
compactness error          0
concavity error            0
concave points error       0
symmetry error             0
fractal dimension error    0
worst radius               0
worst texture              0
worst perimeter            0
worst area                 0
worst smoothness           0
worst compactness          0
worst concavity            0
worst concave points       0
worst symmetry             0
worst fractal dimension    0
label                      0
dtype: int64

In [10]:
#Check the distribution of the target variables

data_frame['label'].value_counts()

label
1    357
0    212
Name: count, dtype: int64

In [11]:
#Seperate the features and the target variables
X = data_frame.drop(columns='label' , axis=1)

Y = data_frame['label']

In [12]:
print(X )

     mean radius  mean texture  mean perimeter  mean area  mean smoothness  \
0          17.99         10.38          122.80     1001.0          0.11840   
1          20.57         17.77          132.90     1326.0          0.08474   
2          19.69         21.25          130.00     1203.0          0.10960   
3          11.42         20.38           77.58      386.1          0.14250   
4          20.29         14.34          135.10     1297.0          0.10030   
..           ...           ...             ...        ...              ...   
564        21.56         22.39          142.00     1479.0          0.11100   
565        20.13         28.25          131.20     1261.0          0.09780   
566        16.60         28.08          108.30      858.1          0.08455   
567        20.60         29.33          140.10     1265.0          0.11780   
568         7.76         24.54           47.92      181.0          0.05263   

     mean compactness  mean concavity  mean concave points  mea

In [13]:
print(Y
      )

0      0
1      0
2      0
3      0
4      0
      ..
564    0
565    0
566    0
567    0
568    1
Name: label, Length: 569, dtype: int64


In [14]:
# change the values in to a numpy asrray
X = np.asarray(X)

Y = np.asarray(Y)

In [15]:
print(X)
# print(Y)

[[1.799e+01 1.038e+01 1.228e+02 ... 2.654e-01 4.601e-01 1.189e-01]
 [2.057e+01 1.777e+01 1.329e+02 ... 1.860e-01 2.750e-01 8.902e-02]
 [1.969e+01 2.125e+01 1.300e+02 ... 2.430e-01 3.613e-01 8.758e-02]
 ...
 [1.660e+01 2.808e+01 1.083e+02 ... 1.418e-01 2.218e-01 7.820e-02]
 [2.060e+01 2.933e+01 1.401e+02 ... 2.650e-01 4.087e-01 1.240e-01]
 [7.760e+00 2.454e+01 4.792e+01 ... 0.000e+00 2.871e-01 7.039e-02]]


In [16]:
model = SVC()

In [17]:
# hyperparameters

parameters = {
   'kernel':['linear','poly','rbf','sigmoid'],
   'C':[1,5,10,20]
}

In [18]:
classifier = GridSearchCV(model, parameters , cv = 5 )

In [19]:
classifier.fit(X,Y)

GridSearchCV(cv=5, estimator=SVC(),
             param_grid={'C': [1, 5, 10, 20],
                         'kernel': ['linear', 'poly', 'rbf', 'sigmoid']})

In [20]:
classifier.cv_results_

{'mean_fit_time': array([2.70589976e+00, 8.27226639e-03, 7.40818977e-03, 4.10785198e-02,
        5.69477525e+00, 3.96881104e-03, 4.45623398e-03, 1.47376060e-02,
        7.02718806e+00, 4.44922447e-03, 4.23855782e-03, 1.47801399e-02,
        7.82293010e+00, 4.50429916e-03, 4.38928604e-03, 1.53019428e-02]),
 'std_fit_time': array([9.49677994e-01, 2.90998144e-03, 4.68889532e-04, 1.74367895e-02,
        3.88253905e+00, 3.37658408e-04, 3.34046786e-04, 4.31022996e-04,
        1.59797023e+00, 2.47432616e-04, 2.16665350e-04, 6.16836456e-04,
        2.47435335e+00, 8.57389277e-05, 3.34961456e-04, 6.01290957e-04]),
 'mean_score_time': array([0.00160699, 0.00260668, 0.00295401, 0.01859708, 0.00107322,
        0.00111718, 0.00191984, 0.00381246, 0.00131798, 0.00128531,
        0.0015831 , 0.00371165, 0.00117598, 0.00110741, 0.00170488,
        0.00376525]),
 'std_score_time': array([2.99719500e-04, 7.35185273e-04, 2.97423599e-04, 1.54096296e-02,
        1.68813823e-05, 2.03802009e-05, 5.62608877e-

In [21]:
# Find the best parameters
best_parameters = classifier.best_params_

In [22]:
print(best_parameters)

{'C': 10, 'kernel': 'linear'}


In [23]:
#highestaccuracy
highest_accuracy = classifier.best_score_

In [24]:
print(highest_accuracy)

0.9525694767893185


In [25]:
result = pd.DataFrame(classifier.cv_results_)

In [26]:
result.head()

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0       2.705900      0.949678         0.001607        0.000300       1   
1       0.008272      0.002910         0.002607        0.000735       1   
2       0.007408      0.000469         0.002954        0.000297       1   
3       0.041079      0.017437         0.018597        0.015410       1   
4       5.694775      3.882539         0.001073        0.000017       5   

  param_kernel                         params  split0_test_score  \
0       linear   {'C': 1, 'kernel': 'linear'}           0.947368   
1         poly     {'C': 1, 'kernel': 'poly'}           0.842105   
2          rbf      {'C': 1, 'kernel': 'rbf'}           0.850877   
3      sigmoid  {'C': 1, 'kernel': 'sigmoid'}           0.543860   
4       linear   {'C': 5, 'kernel': 'linear'}           0.947368   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.929825           0.973684           0.921053           0.955752   
1           0.885965           0.929825           0.947368           0.938053   
2           0.894737           0.929825           0.947368           0.938053   
3           0.456140           0.464912           0.385965           0.451327   
4           0.938596           0.973684           0.929825           0.964602   

   mean_test_score  std_test_score  rank_test_score  
0         0.945536        0.018689                4  
1         0.908663        0.039382               12  
2         0.912172        0.035444               11  
3         0.460441        0.050253               13  
4         0.950815        0.016216                2

In [27]:
grid_search_result = result[['param_C','param_kernel','mean_test_score']]

In [28]:
grid_search_result

param_C param_kernel  mean_test_score
0        1       linear         0.945536
1        1         poly         0.908663
2        1          rbf         0.912172
3        1      sigmoid         0.460441
4        5       linear         0.950815
5        5         poly         0.922729
6        5          rbf         0.931501
7        5      sigmoid         0.411178
8       10       linear         0.952569
9       10         poly         0.920975
10      10          rbf         0.922714
11      10      sigmoid         0.402391
12      20       linear         0.949061
13      20         poly         0.919221
14      20          rbf         0.920944
15      20      sigmoid         0.398867

In [29]:
import altair as alt

chart = alt.Chart(grid_search_result).mark_point().encode(
    x='param_C',
    y='mean_test_score',
    color='param_kernel',
    tooltip=['param_C', 'param_kernel', 'mean_test_score']
).interactive()

chart


alt.Chart(...)

In [30]:
#from the above graph the highest accuracy is : 95%
#and the best parameters are :{C:10 , kernel: linear}

In [31]:
# RandomizedSearchCV
# loading the support vector classifier
model = SVC()

In [32]:
# hyperparameters
parameters = {
    'kernel':['linear','sigmoid','poly','rbf'],
    'C':[1,5,10,20]
}

In [33]:
#randomizedsearchCV
classifier = RandomizedSearchCV(model,parameters,cv=5)
#give the model , parameters , crossvalidationsocre(cv)

In [34]:
#fitting the data to our model
classifier.fit(X,Y)

RandomizedSearchCV(cv=5, estimator=SVC(),
                   param_distributions={'C': [1, 5, 10, 20],
                                        'kernel': ['linear', 'sigmoid', 'poly',
                                                   'rbf']})

In [38]:
crassvalidation_results = classifier.cv_results_

In [36]:
# best parameters
classifier.best_params_

{'kernel': 'linear', 'C': 10}

In [37]:
# highest accuracy
classifier.best_score_

0.9525694767893185

In [41]:
result = pd.DataFrame(crassvalidation_results)

In [42]:
result

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_kernel  \
0       0.018026      0.004573         0.003730        0.000203      sigmoid   
1       0.004012      0.000125         0.001259        0.000060         poly   
2       0.004897      0.000277         0.001862        0.000137          rbf   
3       0.004077      0.000337         0.001135        0.000009         poly   
4       0.004670      0.000548         0.001159        0.000053         poly   
5       8.133570      2.877488         0.001187        0.000234       linear   
6       0.004462      0.000147         0.001113        0.000025         poly   
7       0.015701      0.000276         0.004238        0.000183      sigmoid   
8       4.884978      1.164519         0.001224        0.000316       linear   
9       0.004157      0.000159         0.001475        0.000044          rbf   

  param_C                          params  split0_test_score  \
0      20  {'kernel': 'sigmoid', 'C': 20}           0.473684   
1       1      {'kernel': 'poly', 'C': 1}           0.842105   
2       1       {'kernel': 'rbf', 'C': 1}           0.850877   
3       5      {'kernel': 'poly', 'C': 5}           0.885965   
4      10     {'kernel': 'poly', 'C': 10}           0.885965   
5      20   {'kernel': 'linear', 'C': 20}           0.929825   
6      20     {'kernel': 'poly', 'C': 20}           0.877193   
7       1   {'kernel': 'sigmoid', 'C': 1}           0.543860   
8      10   {'kernel': 'linear', 'C': 10}           0.938596   
9      10      {'kernel': 'rbf', 'C': 10}           0.877193   

   split1_test_score  split2_test_score  split3_test_score  split4_test_score  \
0           0.403509           0.421053           0.342105           0.353982   
1           0.885965           0.929825           0.947368           0.938053   
2           0.894737           0.929825           0.947368           0.938053   
3           0.912281           0.921053           0.938596           0.955752   
4           0.921053           0.903509           0.938596           0.955752   
5           0.956140           0.956140           0.938596           0.964602   
6           0.921053           0.903509           0.938596           0.955752   
7           0.456140           0.464912           0.385965           0.451327   
8           0.938596           0.973684           0.947368           0.964602   
9           0.921053           0.912281           0.956140           0.946903   

   mean_test_score  std_test_score  rank_test_score  
0         0.398867        0.047640               10  
1         0.908663        0.039382                8  
2         0.912172        0.035444                7  
3         0.922729        0.023689                3  
4         0.920975        0.024701                5  
5         0.949061        0.012816                2  
6         0.919221        0.027300                6  
7         0.460441        0.050253                9  
8         0.952569        0.014200                1  
9         0.922714        0.027879                4

In [43]:
randomized_search_result = result[['param_C','param_kernel','mean_test_score']]

In [44]:
randomized_search_result

param_C param_kernel  mean_test_score
0      20      sigmoid         0.398867
1       1         poly         0.908663
2       1          rbf         0.912172
3       5         poly         0.922729
4      10         poly         0.920975
5      20       linear         0.949061
6      20         poly         0.919221
7       1      sigmoid         0.460441
8      10       linear         0.952569
9      10          rbf         0.922714

In [45]:
# from the above data we have the best  parametes and the best accuracy score
# best parameters : C:10 , kernel:linear
# highest_accuracy = 95.2%